sudo: false

language: java

jdk:
  - oraclejdk8
  - openjdk7

install: mvn -B install -U -DskipTests=true

script: mvn -B verify -U -Dmaven.javadoc.skip=true

after_success:

cache:
  directories:
  - $HOME/.m2

env:
  global:

branches:
  only:
    - master
    